#!/usr/bin/env bash
# This script connects to a server using SSH with a specific private key
# Define the server's IP or hostname
SERVER="8.8.8.8"
# Use SSH with single-character flags to connect
ssh -i ~/.ssh/school ubuntu@$SERVER
