#!/usr/bin/env bash
# Transfers a file from client to server using scp

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables for clarity
path_to_file=$1
ip=$2
username=$3
path_to_key=$4

# Transfer file using scp
# -i: identity file (private key)
# -o StrictHostKeyChecking=no: disable strict host key checking
scp -i "$path_to_key" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip":~/
